# tasks/pre_tasks.yml
---
- name: Wait for apt lock to be released
  ansible.builtin.shell: |
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      echo "Waiting for apt lock...";
      sleep 5;
    done
  changed_when: false
  timeout: 300
  tags: [base, apt]

- name: Ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # Won't update if updated in the last hour
  tags: [base, apt]
