# tasks/main.yml
---
- name: Install QEMU Guest Agent
  ansible.builtin.include_tasks: qemu_agent.yml
  when: monitoring_qemu_agent_enabled

- name: Install Node Exporter
  ansible.builtin.include_tasks: node_exporter.yml
  when: monitoring_node_exporter_enabled
