# tasks/node_exporter.yml
---
- name: Create node_exporter system group
  ansible.builtin.group:
    name: "{{ monitoring_node_exporter_group }}"
    system: true
    state: present

- name: Create node_exporter system user
  ansible.builtin.user:
    name: "{{ monitoring_node_exporter_user }}"
    group: "{{ monitoring_node_exporter_group }}"
    system: true
    shell: "/usr/sbin/nologin"
    create_home: false
    state: present

- name: Check if Node Exporter binary exists
  ansible.builtin.stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter_bin

- name: Get current Node Exporter version
  ansible.builtin.command: "/usr/local/bin/node_exporter --version"
  register: node_exporter_version_check
  changed_when: false
  failed_when: false
  when: node_exporter_bin.stat.exists

- name: Download and Unarchive Node Exporter
  block:
    - name: Download Node Exporter tarball
      ansible.builtin.unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ monitoring_node_exporter_version }}/node_exporter-{{ monitoring_node_exporter_version }}.linux-{{ monitoring_arch_map[ansible_architecture] }}.tar.gz"
        dest: "/tmp"
        remote_src: true
        creates: "/tmp/node_exporter-{{ monitoring_node_exporter_version }}.linux-{{ monitoring_arch_map[ansible_architecture] }}/node_exporter"

    - name: Move binary to /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ monitoring_node_exporter_version }}.linux-{{ monitoring_arch_map[ansible_architecture] }}/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: "0755"
        owner: "{{ monitoring_node_exporter_user }}"
        group: "{{ monitoring_node_exporter_group }}"
        remote_src: true
      notify: Restart node_exporter
  when: >
    not node_exporter_bin.stat.exists or
    (monitoring_node_exporter_version not in node_exporter_version_check.stdout)

- name: Create Systemd Service for Node Exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"
  notify: Restart node_exporter
  tags: [monitoring, systemd]
