# tasks/qemu_agent.yml
---
- name: Install QEMU Guest Agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
    update_cache: true
  notify: Restart qemu-guest-agent
  tags: [monitoring, proxmox]

- name: Ensure QEMU Guest Agent is started
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
  tags: [monitoring, proxmox]
