apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../patches/resource-ingress-extras.yaml

patches:
  - path: ../../patches/fix-admin-pvc.yaml
    target:
      kind: StatefulSet
      name: seaweedfs-admin
