# Made for application set

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: arr-cert-manager
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/sinhaaritro/platform-stack.git
#     targetRevision: HEAD
#     path: kubernetes/clusters/arr/cert-manager
#   destination:
#     server: https://arr-api.example.com:6443
#     namespace: cert-manager
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
