# defaults/main.yml

# Node Exporter Configuration
monitoring_node_exporter_enabled: true
monitoring_node_exporter_version: "1.8.2"
monitoring_node_exporter_user: "node_exporter"
monitoring_node_exporter_group: "node_exporter"
monitoring_node_exporter_port: 9100

# Architecture mapping for download URLs
monitoring_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"

# QEMU Guest Agent (For Proxmox)
monitoring_qemu_agent_enabled: true
