apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    version: 14.6.0
    releaseName: minio
    namespace: storage
    includeCRDs: true
    valuesFile: values.yaml
