apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: minio
    repo: https://cloudpirates.github.io/helm-charts
    version: 0.8.2
    releaseName: minio
    namespace: storage
    includeCRDs: true
    valuesFile: values.yaml
