apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-scale-down.yaml
    target:
      kind: Deployment
      name: longhorn-ui
      namespace: longhorn-system
  - path: patch-scale-down.yaml
    target:
      kind: Deployment
      name: longhorn-driver-deployer
      namespace: longhorn-system
  - path: patch-scale-down.yaml
    target:
      kind: DaemonSet
      name: longhorn-manager
      namespace: longhorn-system
