apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment|StatefulSet
      name: .*
  - path: patch-args-ingester.yaml
    target:
      kind: StatefulSet
      name: mimir-ingester.*
  - path: patch-args-distributor.yaml
    target:
      kind: Deployment
      name: mimir-distributor.*
  - path: patch-args-store-gateway.yaml
    target:
      kind: StatefulSet
      name: mimir-store-gateway.*
  - path: patch-args-ruler.yaml
    target:
      kind: Deployment
      name: mimir-ruler.*
  - path: patch-args-alertmanager.yaml
    target:
      kind: StatefulSet
      name: mimir-alertmanager.*
