apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment|StatefulSet
      name: .*
  - path: patch-no-ha-args.yaml
    target:
      kind: Deployment|StatefulSet
      name: mimir-(ingester|store-gateway|alertmanager|compactor|distributor|querier|query-frontend|query-scheduler|ruler|overrides-exporter).*
