- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "-alertmanager.sharding-ring.replication-factor=1"
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "-alertmanager.sharding-ring.zone-awareness-enabled=false"
