apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - podinfo/kustomization.yaml
  - sealed-secrets/kustomization.yaml
  - cert-manager/kustomization.yaml
  - metallb-system/kustomization.yaml
  - traefik/kustomization.yaml
  - prometheus-stack/kustomization.yaml
  - loki/kustomization.yaml
  # - longhorn/kustomization.yaml
  - kyverno/kustomization.yaml
  - system-patches/kustomization.yaml
