# defaults/main.yml
---
# Version to install (Must be exact version now, not 'latest')
helm_version: "v3.16.2"

# Architecture Mapping
helm_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"

# User for shell completion
helm_user: "{{ ansible_user }}"
