apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/services/podinfo/base
  - allow-ui-netpol.yaml # Adding a cluster-specific resource

namespace: podinfo

secretGenerator:
  - name: podinfo-auth
    literals:
      - username=admin
      - password=secure-tenant-a-password

patches:
  - path: patch-ingress.yaml
  - path: patch-secrets.yaml
