apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/services/podinfo/overlays/dev

namespace: podinfo

patches:
  - path: patch-ingress.yaml
  - path: patch-log-level.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: podinfo
  - path: ../../../apps/maintenance/patch-scale-zero.yaml
    target:
      kind: Deployment
      name: .*
