apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-podinfo
  namespace: podinfo
spec:
  rules:
    - host: podinfo.ruth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-podinfo
                port:
                  number: 9898
