apiVersion: kustomize.config.k8s.io/v1beta1
kind: Deployment
metadata:
  name: my-podinfo
  namespace: podinfo
spec:
  template:
    spec:
      containers:
        - name: podinfo
          env:
            - name: PODINFO_UI_MESSAGE
              value: "Welcome Tenant A"
            # Injecting User/Pass as env vars
            - name: MY_APP_USER
              valueFrom:
                secretKeyRef:
                  name: podinfo-auth
                  key: username
            - name: MY_APP_PASS
              valueFrom:
                secretKeyRef:
                  name: podinfo-auth
                  key: password
