apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-master
  namespace: storage
spec:
  rules:
    - host: master.seaweedfs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-master
                port:
                  number: 9333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-filer
  namespace: storage
spec:
  rules:
    - host: filer.seaweedfs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-filer
                port:
                  number: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-s3
  namespace: storage
spec:
  rules:
    - host: s3.seaweedfs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-webdav
  namespace: storage
spec:
  rules:
    - host: webdav.seaweedfs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-webdav
                port:
                  number: 7333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-volume
  namespace: storage
spec:
  rules:
    - host: volume.seaweedfs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-volume
                port:
                  number: 8080
