apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-admin-secret
  namespace: storage
spec:
  encryptedData:
    adminUser: CHANGE_ME_WITH_KUBESEAL
    adminPassword: CHANGE_ME_WITH_KUBESEAL
