apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer-client
  namespace: storage
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: filer
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: swfs-filer
    - port: 18888
      targetPort: 18888
      protocol: TCP
      name: swfs-grpc
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: filer
