apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: webdav
    app.kubernetes.io/instance: seaweedfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: seaweedfs-4.0.407
  name: seaweedfs-webdav
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webdav
      app.kubernetes.io/instance: seaweedfs
      app.kubernetes.io/name: seaweedfs
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webdav
        app.kubernetes.io/instance: seaweedfs
        app.kubernetes.io/name: seaweedfs
        helm.sh/chart: seaweedfs-4.0.407
    spec:
      containers:
        - command:
            - /bin/sh
            - -ec
            - |
              exec /usr/bin/weed \
              -logtostderr=true \
              -v=1 \
              webdav \
              -ip.bind=0.0.0.0 \
              -port=7333 \
              -filer=seaweedfs-filer-client.storage:8888
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: chrislusf/seaweedfs:4.07
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 20
            tcpSocket:
              port: 7333
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          name: seaweedfs
          ports:
            - containerPort: 7333
              name: swfs-webdav
          readinessProbe:
            failureThreshold: 100
            tcpSocket:
              port: 7333
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
      enableServiceLinks: false
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webdav
    app.kubernetes.io/instance: seaweedfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: seaweedfs-4.0.407
  name: seaweedfs-webdav
  namespace: storage
spec:
  ports:
    - name: swfs-webdav
      port: 7333
      protocol: TCP
      targetPort: 7333
  selector:
    app.kubernetes.io/component: webdav
    app.kubernetes.io/instance: seaweedfs
    app.kubernetes.io/name: seaweedfs
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-webdav
  namespace: storage
spec:
  rules:
    - host: webdav.seaweedfs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-webdav
                port:
                  number: 7333
