# meta/main.yml
---
galaxy_info:
  author: Aritro
  role_name: kubeadm
  namespace: internal
  description: Installs Kubelet, Kubeadm, and Kubectl with system hardening for production.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions: [all]

dependencies:
  - role: k8s_repo
