# meta/main.yml
galaxy_info:
  author: Aritro
  role_name: kubeadm
  namespace: internal
  description: Installs and initializes a Kubernetes cluster using Kubeadm.
  company: None
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - k8s
    - kubeadm
    - production

dependencies:
  # We need a container runtime. The 'docker' role installs containerd.io.
  - role: docker
