apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/longhorn/overlays/minimal
  - ingress.yaml
  # - ../../../apps/infrastructure/longhorn/overlays/maintenance
