apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/longhorn/base
  - ingress.yaml

components:
  - ../../../apps/infrastructure/longhorn/components/settings
  - ../../../apps/infrastructure/longhorn/components/persistence
  - ../../../apps/infrastructure/longhorn/components/tolerations
  - ../../../apps/infrastructure/longhorn/components/persistence-replication0
  # - ../../../apps/infrastructure/longhorn/components/metrics # Requires ServiceMonitor CRD (Circular Dependency)
  - ../../../apps/infrastructure/longhorn/components/minimal
