apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/metallb/overlays/minimal

patches:
  - path: pool-patch.yaml
    target:
      kind: IPAddressPool
      name: default-pool
