# tasks/main.yml
---
- name: Fail if architecture is not supported
  ansible.builtin.fail:
    msg: "System architecture {{ ansible_architecture }} is not mapped in defaults/main.yml"
  when: kind_arch_mapping[ansible_architecture] is not defined

- name: Install Kind binary
  ansible.builtin.include_tasks: install.yml

- name: Configure and Create Cluster
  ansible.builtin.include_tasks: cluster.yml
