# tasks/main.yml
---
- name: Setup Kubectl Client
  ansible.builtin.include_tasks: kubectl.yml

- name: Setup Kind Binary
  ansible.builtin.include_tasks: binary.yml

- name: Provision Kind Cluster
  ansible.builtin.include_tasks: cluster.yml

- name: Configure User Access
  ansible.builtin.include_tasks: access.yml
