apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - color-config.yaml

patches:
  - path: patch-replicas.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: podinfo
  - path: patch-color.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: podinfo
