mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: seaweedfs-s3.storage.svc:8333
          region: us-east-1
          access_key_id: mimir
          secret_access_key: mimir
          insecure: true
          signature_version: v4

    blocks_storage:
      s3:
        bucket_name: mimir-tsdb

    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager

    ruler_storage:
      s3:
        bucket_name: mimir-ruler

# Disable MinIO as we use SeaweedFS
minio:
  enabled: false

# Replicas (minimal for now)
ingester:
  persistentVolume:
    size: 2Gi
    storageClass: longhorn

store_gateway:
  persistentVolume:
    size: 2Gi
    storageClass: longhorn

compactor:
  persistentVolume:
    size: 2Gi
    storageClass: longhorn

ruler:
  enabled: true

alertmanager:
  enabled: true

  persistentVolume:
    size: 2Gi
    storageClass: longhorn

# Gateway (Nginx)
nginx:
  enabled: true

meta_monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-stack
  prometheusRule:
    enabled: true
    labels:
      release: prometheus-stack
      prometheus: k8s
      role: alert-rules
