apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.8
    releaseName: metallb
    namespace: metallb-system
    includeCRDs: true

resources:
  - pool.yaml
