apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://charts.bitnami.com/bitnami
    version: 4.14.1
    releaseName: metallb
    namespace: metallb-system
    includeCRDs: true
    valuesInline:
      controller:
        image:
          tag: 0.13.12-debian-11-r5
      speaker:
        image:
          tag: 0.13.12-debian-11-r5

resources:
  - pool.yaml
