apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 6.4.22
    releaseName: metallb
    namespace: metallb-system
    includeCRDs: true

resources:
  - pool.yaml
