apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://charts.bitnami.com/bitnami
    version: 4.1.0
    releaseName: metallb
    namespace: metallb-system
    includeCRDs: true
