apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-webdav
  namespace: storage
spec:
  rules:
    - host: webdav.seaweedfs.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-webdav
                port:
                  number: 7333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-volume
  namespace: storage
spec:
  rules:
    - host: volume.seaweedfs.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-volume
                port:
                  number: 8080
    - host: "*.seaweedfs-volume.seaweedfs.arr.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-volume
                port:
                  number: 8080
