apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/seaweedfs/overlays/prod
  - ../../../apps/infrastructure/seaweedfs/resources/job-create-buckets.yaml
  # - ../../../apps/infrastructure/seaweedfs/overlays/maintenance

patches:
  - path: patch-ingress-hosts.yaml
  - path: patch-storage.yaml
