apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/seaweedfs/overlays/prod

components:
  - ../../../apps/infrastructure/seaweedfs/components/s3-config
  - ../../../apps/infrastructure/seaweedfs/components/replicas-1
  # - ../../../apps/infrastructure/seaweedfs/components/maintenance

patches:
  - path: patch-ingress-hosts.yaml
