apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-seaweedfs-master
  namespace: storage
spec:
  rules:
    - host: master.seaweedfs.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-master
                port:
                  number: 9333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-seaweedfs-filer
  namespace: storage
spec:
  rules:
    - host: filer.seaweedfs.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-filer
                port:
                  number: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-seaweedfs-s3
  namespace: storage
spec:
  rules:
    - host: s3.seaweedfs.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-seaweedfs-admin
  namespace: storage
spec:
  rules:
    - host: admin.seaweedfs.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-admin
                port:
                  number: 23646
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-webdav
  namespace: storage
spec:
  rules:
    - host: webdav.seaweedfs.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-webdav
                port:
                  number: 7333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-volume
  namespace: storage
spec:
  rules:
    - host: volume.seaweedfs.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-volume
                port:
                  number: 8080
    - host: "*.seaweedfs-volume.seaweedfs.arr.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-volume
                port:
                  number: 8080
