service:
  enabled: true
  type: ClusterIP
  port: 9898

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: placeholder.local
      paths:
        - path: /
          pathType: ImplementationSpecific

serviceMonitor:
  enabled: true
  interval: 15s

tls:
  enabled: true
  certPath: /data/cert

resources:
  limits:
    cpu: 50m
    memory: 64Mi
