- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "-ingester.ring.replication-factor=1"
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "-ingester.ring.zone-awareness-enabled=false"
