provider:
  name: aws

env:
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /etc/kubernetes/secrets/credentials

extraVolumeMounts:
  - name: credentials
    mountPath: /etc/kubernetes/secrets
    readOnly: true

extraVolumes:
  - name: credentials
    secret:
      secretName: external-dns-secret

interval: 1m
logLevel: info

sources:
  - service
  - ingress

domainFilters: []
