apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: alertmanager
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: alertmanager
    namespace: monitoring
    version: 1.33.0
    valuesFile: values.yaml

resources:
  - namespace.yaml
