# defaults/main.yml

# Version to install (Pinned for stability)
# You can override this in group_vars if needed
kubectl_version: "v1.32.0"

# Architecture mapping (Ansible -> Kubernetes naming)
kubectl_arch_mapping:
  x86_64: amd64
  aarch64: arm64

# Installation path
kubectl_bin_path: "/usr/local/bin/kubectl"
