apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - resource-ingress-extras.yaml

patches:
  - path: fix-admin-pvc.yaml
    target:
      kind: StatefulSet
      name: seaweedfs-admin
