apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimir-gateway
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mimir.ruth.example.com
      secretName: mimir-gateway-tls
  rules:
    - host: mimir.ruth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mimir-nginx
                port:
                  number: 80
