# defaults/main.yml
---
# Cluster Identity
kind_cluster_name: "dev-cluster"

# Kind Binary Version
kind_version: "v0.26.0"

# Host Port Mapping (Exposed on the VM IP)
# Override these in your inventory if needed (e.g., if Port 80 is busy)
kind_port_http: 80
kind_port_https: 443
kind_port_extra_1: 8080
kind_port_extra_2: 8443

# Container Port Mapping (Inside the Kind Node)
# Usually keeps standard ports to match Ingress Controller defaults
kind_container_http: 80
kind_container_https: 443
kind_container_extra_1: 8080
kind_container_extra_2: 8443

# Architecture mapping
kind_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"
