apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ../../../apps/infrastructure/grafana/base

components:
  - ../../../apps/infrastructure/grafana/components/storage-longhorn
  - ../../../apps/infrastructure/grafana/components/datasource-loki
  - ../../../apps/infrastructure/grafana/components/datasource-mimir
  # - ../../../apps/infrastructure/grafana/components/maintenance

patches:
  - path: patch-ingress.yaml
