apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian

helmCharts:
  - name: obsidian
    repo: https://x-tructure.github.io/helm-charts
    releaseName: obsidian
    namespace: obsidian
    version: 0.1.5
    valuesFile: values.yaml

resources:
  - namespace.yaml
