apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |
    backup-target: 
    backup-target-credential-secret: 
    allow-recurring-job-while-volume-detached: "false"
    create-default-disk-labeled-nodes: "false"
    default-data-path: /data/storage
    replica-soft-anti-affinity: "false"
    replica-auto-balance: "best-effort"
    storage-over-provisioning-percentage: "200"
    storage-minimal-available-percentage: "25"
    upgrade-checker: "false"
    default-replica-count: "3"
    default-data-locality: "best-effort"
    backup-store-poll-interval: "300"
    taint-toleration: "node-role.kubernetes.io/control-plane:NoSchedule"
    system-managed-components-node-selector: 
    priority-class: 
    auto-salvage: "true"
    auto-delete-pod-when-volume-detached-unexpectedly: "true"
    disable-scheduling-on-cordoned-node: "true"
    replica-zone-soft-anti-affinity: "true"
    node-down-pod-deletion-policy: "do-nothing"
    allow-node-drain-with-last-healthy-replica: "false"
    mkfs-ext4-parameters: 
    disable-replica-rebuild: "false"
    replica-replenishment-wait-interval: "600"
    concurrent-replica-rebuild-per-node-limit: "5"
    concurrent-volume-backup-restore-per-node-limit: "5"
    disable-revision-counter-check: "false"
    system-managed-pods-image-pull-policy: "if-not-present"
    allow-volume-creation-with-degraded-availability: "true"
    auto-cleanup-system-generated-snapshot: "true"
    concurrent-automatic-engine-upgrade-per-node-limit: "5"
    backing-image-cleanup-wait-interval: "60"
    backing-image-recovery-wait-interval: "300"
    guaranteed-engine-manager-cpu: "12"
    guaranteed-replica-manager-cpu: "12"
    kubernetes-cluster-autoscaler-enabled: "false"
    orphan-auto-deletion: "false"
    storage-network: 
    reclaim-policy: "Delete"
    allow-empty-node-selector-volume: "true"
    allow-empty-disk-selector-volume: "true"
    disable-snapshot-purge: "false"
    snapshot-max-count: "250"
