apiVersion: v1
kind: Secret
metadata:
  name: velero-aws-creds
  namespace: velero
type: Opaque
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gVmVRNjRJQW8yV3VVaExEWE1xNXQKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gdVpYZFFhMUxCQWxlQWFwNUV3U2F4REgwNVhidFhieW5mck9JZTU0Qwo=
