apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-security-context.yaml
    target:
      kind: Deployment
      name: authentik-server
  - path: patch-security-context.yaml
    target:
      kind: Deployment
      name: authentik-worker
