apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/infrastructure/alertmanager/base
  - ingress.yaml

components:
  - ../../../apps/infrastructure/alertmanager/components/resources
  - ../../../apps/infrastructure/alertmanager/components/persistence
