apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-ingress
  namespace: storage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
    - hosts:
        - s3.ruth.example.com
        - filerseaweed.ruth.example.com
        - seaweedfs.ruth.example.com
        - admin.seaweedfs.ruth.example.com
      secretName: seaweedfs-cert
  rules:
    - host: s3.ruth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333
    - host: filerseaweed.ruth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-filer
                port:
                  number: 8888
    - host: seaweedfs.ruth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-master
                port:
                  number: 9333
    - host: admin.seaweedfs.ruth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-master
                port:
                  number: 23646
