apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ../../../apps/infrastructure/seaweedfs/overlays/prod

components:
  - ../../../apps/infrastructure/seaweedfs/components/bucket-job

patches:
  - path: patch-ingress.yaml
  - path: patch-storage.yaml
