apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ../../../apps/infrastructure/seaweedfs/overlays/prod

components:
  - ../../../apps/infrastructure/seaweedfs/components/s3-config
  - ../../../apps/infrastructure/seaweedfs/components/replicas-1
  - ../../../apps/infrastructure/seaweedfs/components/storage-longhorn
  # - ../../../apps/infrastructure/seaweedfs/components/maintenance # Uncomment to scale down statefulsets

patches:
  - path: patch-ingress.yaml
