apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/seaweedfs/base
  # - ../../../apps/infrastructure/seaweedfs/overlays/maintenance

patches:
  # Ingress Host Configuration
  - path: patch-ingress-hosts.yaml
  # Maintenance Mode (Scale to Zero)
  # Uncomment to completely shut down SeaweedFS data nodes
  # - path: ../../../apps/maintenance/patch-scale-zero.yaml
  #   target:
  #     kind: Deployment|StatefulSet
  #     name: .*
