apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ../../../apps/infrastructure/seaweedfs/overlays/prod
  - ../../../apps/infrastructure/seaweedfs/resources/job-create-buckets.yaml

patches:
  - path: patch-ingress-hosts.yaml
