apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ../../../apps/infrastructure/seaweedfs/base

patches:
  # Ingress Host Configuration
  - path: patch-ingress-hosts.yaml
