# meta/main.yml
---
galaxy_info:
  author: Aritro
  role_name: argocd
  description: Installs ArgoCD Core into a Kubernetes Cluster.
  company: None
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags: [kubernetes, gitops, argocd]

dependencies:
  # Requires a running cluster (handled by kind or kubeadm roles previously)
  - role: kubectl
