# meta/main.yml
---

galaxy_info:
  author: Aritro
  role_name: helm
  namespace: internal
  description: Installs the Helm package manager for Kubernetes.
  company: None
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - k8s
    - helm
    - packagemanager

dependencies: []
