# meta/main.yml
---
galaxy_info:
  author: Aritro
  role_name: helm
  namespace: internal
  description: Installs the Helm package manager via official Apt repositories.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions: [all]

dependencies: []
