# meta/main.yml
galaxy_info:
  author: Aritro
  role_name: kubectl
  namespace: internal
  description: Installs the Kubernetes command-line tool (kubectl) with checksum verification.
  company: None
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - k8s
    - client
    - cli

dependencies: []
