apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - secrets.yaml

patches:
  - path: patch-secrets.yaml
    target:
      kind: Deployment
      name: authentik-server
  - path: patch-secrets.yaml
    target:
      kind: Deployment
      name: authentik-worker
