apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  namespace: security
spec:
  template:
    spec:
      containers:
        - name: authentik
          envFrom:
            - secretRef:
                name: authentik-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: security
spec:
  template:
    spec:
      containers:
        - name: authentik
          envFrom:
            - secretRef:
                name: authentik-secrets
