# handlers/main.yml

- name: Restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Update ca-certificates
  ansible.builtin.command: update-ca-certificates
  changed_when: true
