# tasks/init.yml
---
- name: Check if cluster is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_conf

- name: Initialize Kubeadm (Primary)
  ansible.builtin.command: >
    kubeadm init
    --pod-network-cidr={{ kubeadm_pod_network_cidr }}
    --service-cidr={{ kubeadm_service_cidr }}
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    {{ '--control-plane-endpoint=' + kubeadm_control_plane_endpoint if kubeadm_control_plane_endpoint else '' }}
    {{ '--upload-certs' if kubeadm_control_plane_endpoint else '' }}
  register: init_output
  when: not k8s_admin_conf.stat.exists
  changed_when: true

- name: Create .kube directory for dev user
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy admin.conf to user home
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
