apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    namespace: monitoring
    version: 1.6.0
    includeCRDs: true
    valuesFile: values.yaml
