apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus-node-exporter
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: node-exporter
    namespace: monitoring
    version: 4.51.1
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - path: patch-args.yaml
    target:
      kind: DaemonSet
      name: node-exporter-prometheus-node-exporter
