apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/infrastructure/external-dns/base

components:
  - ../../../apps/infrastructure/external-dns/components/registry-txt-ruth
  - ../../../apps/infrastructure/external-dns/components/provider-cloudflare
  - ../../../apps/infrastructure/external-dns/components/resources
