# defaults/main.yml
---
# Networking
kubeadm_pod_network_cidr: "10.244.0.0/16"
kubeadm_service_cidr: "10.96.0.0/12"
kubeadm_control_plane_endpoint: "" # Set for HA

# CNI
calico_version: "v3.27.0"
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"

# Bootstrap Logic
kubeadm_bootstrap_node: ""  # MUST BE SET IN INVENTORY

# Safety Switches
allow_destructive_reset: false
