apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

resources:
  - ../../../apps/infrastructure/promtail

secretGenerator:
  - name: promtail
    behavior: replace
    files:
      - promtail.yaml=promtail-config.yaml
    options:
      disableNameSuffixHash: true

patches:
  - path: debug-patch.yaml
    target:
      kind: DaemonSet
      name: promtail
  - path: probe-patch.yaml
    target:
      kind: DaemonSet
      name: promtail
