apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/promtail/overlays/minimal

patches:
  - path: ../../../apps/maintenance/patch-daemonset-disable.yaml
    target:
      kind: DaemonSet
      name: .*
