apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

resources:
  - ../../../apps/infrastructure/promtail

patches:
  - path: debug-patch.yaml
    target:
      kind: DaemonSet
      name: promtail
  - target:
      kind: Namespace
      name: logging
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: logging

secretGenerator:
  - name: promtail
    behavior: replace
    files:
      - promtail.yaml=promtail-config.yaml
    options:
      disableNameSuffixHash: true
