apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

resources:
  - ../../../apps/infrastructure/promtail

patches:
  - path: secret-patch.yaml
    target:
      kind: Secret
      name: promtail
  - path: debug-patch.yaml
    target:
      kind: DaemonSet
      name: promtail
  - path: probe-patch.yaml
    target:
      kind: DaemonSet
      name: promtail
  - path: namespace-delete.yaml
    target:
      kind: Namespace
      name: logging
