apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

resources:
  - ../../../apps/infrastructure/loki
  - ingress.yaml

patches:
  - path: sts-patch.yaml
    target:
      kind: StatefulSet
      name: loki
  - target:
      kind: Service
      name: loki
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
