# meta/main.yml
---
galaxy_info:
  author: Aritro
  role_name: kind
  namespace: internal
  description: Installs the Kind cluster manager for Kubernetes.
  company: None
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - k8s
    - kind
    - cluster

dependencies:
  - role: docker
