# meta/main.yml
galaxy_info:
  author: Aritro
  role_name: kind
  namespace: internal
  description: Installs Kind (Kubernetes in Docker) and Kubectl for Dev/Test environments.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - kind
    - dev
    - testing

dependencies:
  - role: k8s_repo
