apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: storage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: selfsigned-issuer
    link.argocd.argoproj.io/external-link: https://longhorn.arr.example.com/
spec:
  tls:
    - hosts:
        - longhorn.arr.example.com
      secretName: longhorn-ui-cert
  rules:
    - host: longhorn.arr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
