# tasks/main.yml
---
- name: Handle Security Packages
  ansible.builtin.import_tasks: packages.yml

- name: Handle SSH Lockdown
  ansible.builtin.import_tasks: ssh.yml

- name: Handle Firewall Rules
  ansible.builtin.import_tasks: firewall.yml

- name: Handle Intrusion Prevention
  ansible.builtin.import_tasks: fail2ban.yml
