apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/cert-manager/base

components:
  - ../../../apps/infrastructure/cert-manager/components/issuers
  - ../../../apps/infrastructure/cert-manager/components/minimal-replicas
  - ../../../apps/infrastructure/cert-manager/components/resource-limits
  # - ../../../apps/infrastructure/cert-manager/components/maintenance
