apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/instance=mimir
  - path: replicas.yaml
    target:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/instance=mimir
