# meta/main.yml
galaxy_info:
  author: Aritro
  role_name: users
  namespace: internal
  description: Role to manage system users, SSH keys, and user-level git config.
  company: None
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - users
    - ssh
    - git

dependencies: []
