# tasks/prerequisites.yml
---
# 1. Disable Swap (Critical for Kubelet)
- name: Disable SWAP (1/2) - Turn off immediately
  ansible.builtin.command: swapoff -a
  changed_when: false # It's a safety check
  tags: [kubeadm, system]

- name: Disable SWAP (2/2) - Remove from /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  tags: [kubeadm, system]

# 2. Kernel Modules
- name: Enable kernel modules for Containerd/K8s
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  tags: [kubeadm, system]

# 3. Sysctl Params
- name: Configure sysctl params for Kubernetes
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { key: "net.ipv4.ip_forward", value: "1" }
  tags: [kubeadm, system]
