apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: [APP_NAME]
    repo: [REPO_URL]
    version: [VERSION]
    releaseName: [RELEASE_NAME]
    namespace: [NAMESPACE]
    valuesFile: values.yaml
