apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      # The chart usually names it 'authentik-server' or just 'authentik' depending on settings.
      # Assuming 'authentik-server' based on standard chart behavior.
      name: authentik-server
