apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/prometheus-stack/overlays/minimal
  - ingress.yaml

patches:
  - target:
      kind: Prometheus
      name: prometheus-stack-kube-prom-prometheus
    patch: |-
      - op: add
        path: /spec/externalLabels
        value:
          cluster: ruth
