apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/kyverno/base

components:
  - ../../../apps/infrastructure/kyverno/components/minimal-replicas
  - ../../../apps/infrastructure/kyverno/components/resource-limits
  - ../../../apps/infrastructure/kyverno/components/pod-security-restricted
