apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    repo: https://grafana-community.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    version: 11.1.0
    valuesFile: values.yaml
