apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-service.yaml
    target:
      group: ""
      version: v1
      kind: Service
      name: seaweedfs-filer-client
      namespace: storage
